
trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: '1.5.0'

- script: |
    cd terraform
    terraform init
    terraform plan
    terraform apply -auto-approve
  displayName: 'Terraform Apply'



